services:
  spotify-bot:
    build: .
    image: rocky-telegram-bot:v1.2.2
    container_name: spotify-telegram-bot
    restart: unless-stopped
    dns:
      - 192.168.86.22
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./data:/app/data
    environment:
      - TELEGRAM_BOT_TOKEN
      - SPOTIFY_CLIENT_ID
      - SPOTIFY_CLIENT_SECRET
      - SPOTIFY_REDIRECT_URI
      - PORT
      - USER_1_ID
      - USER_1_NAME
      - USER_2_ID
      - USER_2_NAME
      - SPOTIFY_PLAYLIST_ID

